# Plan del Día de NumPy

* Creacion de arrays (np.array, np.arange, np.linspace)
* Operaciones vectorizadas (sumas, restas, multiplicaciones)
* reshape y dimensiones
* slicing y acceso a elementos
* broadcasting mágico
* ejercicios para parcticar

In [1]:
# importamos la biblioteca de Numpy
# lo de as np es solo para escribir más corto, así no escribes numpy.array() sino np.array()
import numpy as np

## ¿Qué es un array?
#### Un array en Numpy es como una lista de números, pero mucho más potente y rápida

In [2]:
mi_lista = [1, 2, 3]           # Lista normal de Python
mi_array = np.array(mi_lista)  # Array de NumPy

### ¿Por qué usar arrays en lugar de listas?
* Los arrays ocupan menos memoria
* Permiten operaciones matemáticas directas (sumas, restas...)
* Son más rápidos en cálculos grandes (¡Ideal para ciencia de datos!)

In [3]:
# Ejemplo 1:
a = np.array([10, 20, 30, 40])
print("Array:", a)

Array: [10 20 30 40]


Aunque parece una lista, esto no es una lista de Python, es un array NumPy, lo que significa que puedes hacerle cosas matemáticas directamente

In [4]:
# Ejemplo 2:
a = np.array([10, 20, 30 ,40])
print("Suma +5:", a + 5)
print("Multiplicado por 2:", a * 2)
print("Cuadrado:", a ** 2)

# Esto no se puede hacer tan fácil con listas normales

Suma +5: [15 25 35 45]
Multiplicado por 2: [20 40 60 80]
Cuadrado: [ 100  400  900 1600]


## Visualización

### Imagina el array como una fila de cajitas con números dentro:

[10] [20]  [30]  [40]

Cuando haces a + 5, le estás diciendo:
"Ey NumPy, suma 5 a cada cajita".
Y NumPy lo hace en paralelo, sin bucles. ¡Por eso es tan rápido!

In [5]:
mis_puntos = np.array([10, 6, 8, 2, 12, 4])
print("Mis puntos originales:", mis_puntos)
print("Puntos +1 punto de premio:", mis_puntos + 1 )
print("Puntos * 20:", mis_puntos * 20)
print("La mitad de mis puntos:", mis_puntos / 2)
print("La media de mis puntos:", mis_puntos.mean())
print("La mediana de mis puntos:", np.median(mis_puntos))

Mis puntos originales: [10  6  8  2 12  4]
Puntos +1 punto de premio: [11  7  9  3 13  5]
Puntos * 20: [200 120 160  40 240  80]
La mitad de mis puntos: [5. 3. 4. 1. 6. 2.]
La media de mis puntos: 7.0
La mediana de mis puntos: 7.0


## LECCIÓN 2: Arrays 2D — Mini-tablas y matrices


## 🧩 ¿Qué es un array 2D?
### Un array 2D es como una tabla de filas y columnas, como si fuera una hoja de Excel o una matriz matemática.

In [6]:
tabla = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(tabla)

# Tiene 3 filas y 3 columnas --> Se llama un array de forma (3, 3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# Ver forma y dimensiones

print("Forma:", tabla.shape)       # (filas, columnas)
print("Dimensiones:", tabla.ndim)  # Cuántas dimensiones tiene (2 en este caso)

Forma: (3, 3)
Dimensiones: 2


### Visualizacion de la estructura

<pre> ``` columnas → 0 1 2
┌────────────
0 │ 1 2 3
1 │ 4 5 6
2 │ 7 8 9
↑
filas ``` </pre>

## 🔪 SLICING — Seleccionar partes
### Como si cortaras la tabla:

In [8]:
print(tabla[0])       # Primera fila -> [1 2 3]
print(tabla[:, 0])    # Primera columna -> [1 4 7]
print(tabla[1, 2])    # Fila 1, columna 2 -> 6

[1 2 3]
[1 4 7]
6


| código       |  ¿Qué devuelve?     |
|--------------|-------------------  |
|tabla[0]      | Fila o completa     |
|tabla [:, 0]  | Columna 0 completa  |
|tabla[1, 2]   | Elemento fila 1,columna 2

Se cuenta desde 0, como en Python, fila 1 es la segunda fila.

## Operaciones con arrays 2D

In [9]:
print("Suma total:", tabla.sum())
print("Suma por filas:", tabla.sum(axis=1))     # Horizontal
print("Suma por columnas:", tabla.sum(axis=0)) # Vertical

# axis = 0 -> columna,
# axis = 1 -> fila.

Suma total: 45
Suma por filas: [ 6 15 24]
Suma por columnas: [12 15 18]


### 🧪 EJERCICIO 2 — Tu propia tabla
#### * Crea una tabla NumPy de 3x4 con tus propios números.

* Imprime:

* La forma y dimensiones

* Una fila y una columna

* La suma total, por filas y por columnas



In [10]:
tabla2 = np.array([
    [2, 4, 6, 2],
    [3, 0, 2, 3],
    [1, 5, 9, 7]

])
print(tabla2)
print("Forma:", tabla2.shape)           # Forma
print("Dimensiones:", tabla2.ndim)      # Dimensiones
print(tabla2[1])                        # 1 fila
print(tabla2[:, 1])                     # 1 columna
print("La suma total es:", tabla2.sum())

[[2 4 6 2]
 [3 0 2 3]
 [1 5 9 7]]
Forma: (3, 4)
Dimensiones: 2
[3 0 2 3]
[4 0 5]
La suma total es: 44


## 🎓 LECCIÓN 3: Reshape — Cambiar la forma de un array



### ¿Qué es reshape?
#### Imagina que tienes una lista larga de números y quieres darle forma de tabla, o viceversa, sin cambiar los datos, solo su organización.

In [11]:
a = np.array([1, 2, 3, 4, 5, 6])
print("Array original:", a)

b = a.reshape((2, 3))  #Cambia a 2 filas y 3 columnas
print("Array reshaped a 2 x 3:\n", b)

Array original: [1 2 3 4 5 6]
Array reshaped a 2 x 3:
 [[1 2 3]
 [4 5 6]]


### 📝 Regla fundamental para reshape:
El número total de elementos debe ser el mismo.
En el ejemplo, a tiene 6 elementos, y b es un array 2x3 = 6 elementos

####  ¿Y si pongo un número  -1 en reshape?
####  -1 le dice a NumPy que calcule automáticamente esa dimensión.

In [12]:
b = a.reshape((3, -1))   # 3 filas, columnas las que hagan falta
print(b)
# Es decir, con el -1, reshape calcula por si sola que poner ahi

[[1 2]
 [3 4]
 [5 6]]


### 🧪 Ejercicio 3:
* Crea un array con números del 1 al 12.

* Cámbiale la forma a (3, 4).

* Cámbiale la forma a (2, 6).

* Cámbiale la forma a (-1, 3) y explica qué hace.



In [13]:
 C = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
 print(C)
 forma1 = C.reshape((3, 4))   # Cambia a 3 filas y 4 columnas
 print(forma1)
 forma2 = C.reshape((2, 6))   # Cambia a 2 filas y 6 columnas
 print(forma2)
 forma3 = C.reshape(-1, 3)    # Cambia a 4 columnas y pone las filas que le parece
 print(forma3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## 🎓 LECCIÓN 4: Broadcasting — Operaciones entre arrays de distinta forma

### 🔥 ¿Qué es broadcasting?
#### Broadcasting es lo que permite que NumPy combine arrays de distintas formas y tamaños sin necesidad de bucles.

#### Gracias a esto, puedes hacer operaciones entre matrices y vectores sin escribir loops. NumPy ajusta los tamaños automáticamente si son compatibles.

In [14]:
# Sumar un numero a un array
a = np.array([1, 2, 3])
b = a + 10
print(b)
# NumPy expande el 10 para que se comporte como [10, 10, 10]

[11 12 13]


In [15]:
matriz = np.array([
                   [1, 2, 3],
                   [4, 5, 6]
                   ])
vector = np.array([10, 20, 30])
resultado = matriz+ vector
print(resultado)

# Numpy expande automaticamente vector para que se repita por cada fila

[[11 22 33]
 [14 25 36]]


In [16]:
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
pesos_columna = np.array([[1], [10]])    # 2 filas, 1 columna

resultado = matriz * pesos_columna
print(resultado)

# el primer numero multiplica la primera fila
# el segundo numero multiplica la segunda fila
# este ejemplo es menos intuitivo pero muy ñutil en deep learning

[[ 1  2  3]
 [40 50 60]]


### 📏 ¿Cómo sabe NumPy si puede hacer broadcasting?
#### Debe cumplir la regla de compatibilidad:

* Si las dimensiones son iguales o una de ellas es 1, se pueden alinear.

NumPy expande la dimensión 1 como si fuera un "eco" (broadcasting).

### 🧪 Ejercicio 4:
* Crea una matriz 3x3 con números del 1 al 9.

* Súmale el vector [10, 20, 30] usando broadcasting.

* Multiplica cada fila por un número diferente: [1], [2], [3].

In [17]:
matriz2 = np.array([
    [1,2,3],
    [4, 5, 6],
    [7, 8, 9]
])
vector = [10, 20, 30]
resultado_suma = matriz2 + vector
print(resultado_suma)

multiplicacion = np.array([[1], [2], [3]])
resultado_producto = matriz2 * multiplicacion
print(resultado_producto)

[[11 22 33]
 [14 25 36]
 [17 28 39]]
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


## 🎓 LECCIÓN 5: Indexado booleano — Filtrar con condiciones

### 🧠 ¿Qué es el indexado booleano?
#### Es una forma de elegir elementos de un array usando condiciones, como si aplicaras un filtro lógico.

In [18]:
# Filtrar mayores de 5

q = np.array([1, 3, 5, 7, 9])

filtro = q > 5
print(filtro) # [False False False True True]

resultado = q[filtro]
print(resultado)  # [7 9]

# q > 5 devuelve un array de boleanos
# luego usamos ese array para seleccionar los valores donde es True

[False False False  True  True]
[7 9]


In [19]:
# Atajo directo
print(q[q > 5])   #[7 9]

[7 9]


In [20]:
# Condiciones combinadas

b = np.array([10, 20, 30, 40, 50])

# Seleccionar valores entre 15 y 45
print(b[(b > 15)])    # [20 30 40]

# Usa & para "y", | para "o"
# Los parentesis son obligatorios

[20 30 40 50]


In [21]:
# En arrays 2D

matriz = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Para los mayores de 5
print(matriz[matriz > 5])  # [6 7 8 9]

[6 7 8 9]


### 🧪 Ejercicio 5:
* Crea un array del 1 al 20.

* Filtra todos los pares.

* Filtra los múltiplos de 3 mayores que 10.

* Con una matriz 4x5 del 1 al 20, selecciona los valores mayores que 15.



In [22]:
e = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(e[e % 2 == 0])
print(e[(e % 3 == 0) & (e > 10)])
r = e.reshape((4, 5))
print(r)
print(r[r > 15])

[ 2  4  6  8 10 12 14 16 18 20]
[12 15 18]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[16 17 18 19 20]


## 🎓 LECCIÓN 6: Slicing avanzado — Acceder a partes de arrays

## 📌 ¿Qué es slicing?
#### Slicing es cortar porciones de un array, como si usaras un cuchillo sobre los datos.

#### En NumPy funciona igual que en Python, pero con soporte para arrays multidimensionales.

In [23]:
# Slicing en 1D
a = np.array([10, 20, 30, 40, 50])
print(a[1:4])   # [20 30 40]
# Desde el índice 1 (inclusive) hasta el 4 (exclusivo)

[20 30 40]


In [24]:
# Slicing en 2D
m = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# Formato: m[filas, columnas]

In [25]:
# Acceder a una fila
print(m[0])      # [1 2 3]
print(m[1, :])   # [4 5 6] -> fila 1, todas las columnas

[1 2 3]
[4 5 6]


In [26]:
# Acceder a una columna
print(m[:, 1])   #[2 5 8] -> todas las filas, columna 1

[2 5 8]


In [27]:
# Submatriz
print(m[0:2, 1:3])

# Fila 0 y 1 (excluye la 2), columnas 1 y 2

[[2 3]
 [5 6]]


In [28]:
# índices negativos
print(m[-1])    # Última fila -> [7 8 9]
print(m[:, -1]) # Última columna -> [3 6 9]

[7 8 9]
[3 6 9]


In [29]:
# Copias vs Vistas
# Esto es peligroso si no sabes porque la matriz original cambia
# sub aqui es una vista no una copia
sub = m[0:2, 0:2]
sub[0, 0] = 999
print(m)
# original: m = np.array([
    # [1, 2],
    # [3, 4]
# ])

# despues de igualar sub
# print(m)
# [[999   2]
#  [  3   4]]

[[999   2   3]
 [  4   5   6]
 [  7   8   9]]


### (la diferencia crucial entre = y .copy())

#### Cuando haces sub = m[0:2, 0:2], no estás creando una nueva matriz, solo estás viendo (una vista) una parte de m.

### Modificar sub ➜ modifica directamente m, porque ambas comparten la misma región de memoria.

In [30]:
# Como evitar lo anterior usando .copy()
# Esto si crea una copia real e independiente
sub_copia = m[0:2, 0:2].copy()

### Ejercicios:
* Extrae la fila 1 completa → [50, 60, 70, 80]

* Extrae la columna 2 completa → [30, 70, 110]

* Extrae la submatriz central
* Extrae los 2 últimos valores de cada fila usando slicing, no índices directos.

* Haz una copia de la submatriz del punto 3, modifica uno de sus valores, e imprime x para comprobar que no ha cambiado.

In [31]:
# Este es el array que se usará para el ejercicio

x = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

# Extrae la fila 1 completa
print(x[1, :])

# Extrae la columna 2 completa
print(x[:, 2])

# Extrae la submatriz central [60. 70] (Los numeros del centro)
print(x[1:2, 1:3])

# Extrae los 2 últimos valores de cada fila usando slicing, no índices directos
print(x[:3, 2:])

# Haz una copia de la submatriz del punto 3, modifica uno de sus valores, e imprime x para comprobar que no ha cambiado.
nueva = x[:3, 2:]
nueva = nueva + 10
print(nueva)
print(x)

[50 60 70 80]
[ 30  70 110]
[[60 70]]
[[ 30  40]
 [ 70  80]
 [110 120]]
[[ 40  50]
 [ 80  90]
 [120 130]]
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


## 🎓 LECCIÓN 7 — Estadísticas rápidas con NumPy
### 📊 Funciones estadísticas básicas en NumPy

|Función	    |Qué hace               |
|-------------|-----------------------|
|x.mean()     |Media aritmética       |
|x.std()      |Desviación estándar    |
|x.sum()      |Suma total             |
|x.min()      |Valor mínimo           |
|x.max()      |Valor máximo           |
|x.argmin()   |Índice del valor mínimo|
|x.argmax()   |Índice del valor máximo|

In [32]:
# argmin() y argmax() son muy útiles cuando quieres saber la posicion del mayor o menor valor
# idx = x.argmax()
# print(x[idx])    # imprime 50

In [33]:
# Tambien funciona en matrices
m = np.array([
    [10, 20],
    [30, 20]
])

print(m.mean())         # media total
print(m.mean(axis=0))   # media por columna
print(m.mean(axis=1))   # media por fila

20.0
[20. 20.]
[15. 25.]


## Ejercicio

* Calcula:

  * La media general

  * La media por filas

  * La media por columnas

* Calcula:

  * El mínimo y el máximo

  * Sus posiciones (argmin() y argmax())

* Calcula la desviación estándar

* Usa np.sum(y, axis=1) para sumar cada fila

In [34]:
# Este es el array que usaremos
y = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Media general
print(y.mean())

# Media por filas
print(y.mean(axis=1))

# Media por columna
print(y.mean(axis = 0))

# minimo
print(y.min())

# máximo
print(y.max())

# posicion del minimo y el máximo
print(y.argmin())  # Posicion del minimo (su indice)
print(y.argmax())  # Posicion del maximo (su indice)

# Desviacion estandar
print(y.std())

# Suma de cada fila
print(np.sum(y, axis=1))

50.0
[20. 50. 80.]
[40. 50. 60.]
10
90
0
8
25.81988897471611
[ 60 150 240]


## 🎓 LECCIÓN 8: Funciones Universales (ufuncs)

### 🧠 ¿Qué son las ufuncs?
#### Son funciones matemáticas rápidas y optimizadas que actúan elemento a elemento sobre arrays, sin que tengas que usar bucles.

#### Ejemplos:

|Función	           |Significado|
|--------------------|-----------|
|np.sqrt(x)	         |Raíz cuadrada|
|np.exp(x)	         |Exponencial|
|np.log(x)	         |Logaritmo natural|
|np.sin(x)	         |Seno|
|np.round(x)	       |Redondeo|
|np.clip(x, min, max)|	            Limita los valores entre mínimo y máximo|

In [35]:
x = np.array([1, 2, 3, 4, 5])

print(np.sqrt(x))     # raíz cuadrada
print(np.exp(x))      # exponencial
print(np.clip(x, 2, 4))  # fuerza los valores entre 2 y 4


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[2 2 3 4 4]


## Ejercicio:

* Calcula la raíz cuadrada de x

* Calcula el seno de x

* Multiplica todos los elementos por π y redondéalos

* Aplica clip(x, 3, 8) para limitar los valores entre 3 y 8


In [36]:
# Creamos un array
x = np.linspace(0, 10, 5)   # crea [0, 2.5, 5., 7.5, 10.]
print(x)

# Calcula la raiz cuadrada de x
print(np.sqrt(x))

# Calcula el seno de x
print(np.sin(x))

# Multiplica todos los elementos por π y redondéalos
print(np.round(x * np.pi))

# Aplica clip(x, 3, 8) para limitar los valores entre 3 y 8
print(np.clip(x, 3, 8))


[ 0.   2.5  5.   7.5 10. ]
[0.         1.58113883 2.23606798 2.73861279 3.16227766]
[ 0.          0.59847214 -0.95892427  0.93799998 -0.54402111]
[ 0.  8. 16. 24. 31.]
[3.  3.  5.  7.5 8. ]


## Resumen de lo visto en este Notebook
* 🔢 1. Arrays de NumPy
Crear arrays 1D, 2D y más.

np.array, np.arange, np.linspace, np.zeros, np.ones.

* 🧮 2. Operaciones vectorizadas
Sumar, restar, multiplicar arrays directamente.

Ventajas: rápidas, limpias, sin bucles.

* 📐 3. Reshape y dimensiones
.reshape() para cambiar forma de arrays.

.ndim, .shape, .size.

* 🔍 4. Indexing y slicing
Cortar arrays como si fueran listas.

Usar booleanos para filtrar con condiciones.

* 🌈 5. Broadcasting
Aplicar operaciones entre arrays de distinta forma automáticamente.

Ej: array + escalar, matriz + vector.

* 🪞 6. Copias vs vistas
Arrays pueden compartir memoria (¡cuidado al modificar!).

.copy() evita sorpresas.

* ⚙️ 7. Funciones universales (ufuncs)
np.sqrt(), np.sin(), np.exp(), np.clip(), etc.

Operan elemento a elemento.

* 📊 8. Funciones estadísticas
.mean(), .std(), .sum(), .min(), .max(), .argmin(), .argmax().

También con axis para filas o columnas.